name: Build
run-name: "Build ${{ github.ref_name }} by ${{ github.actor }}"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v3
      - run: typst compile Definition.typ

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: "*.pdf"
